// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1785156213);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1785156213);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1785156217);
user_pref("app.update.lastUpdateTime.region-update-timer", 1785156213);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1785156216);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1785156213);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1785156213);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{3cfdb4b5-b06c-4a65-af72-92b072875a01}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1785156183);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 155);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3ac241d8-a011-4e09-85b9-240f9de7a5c4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.protections_panel.infoMessage.seen", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1785156209244");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1785177809244");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1785156266");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260416072800");
user_pref("browser.startup.homepage_override.mstone", "140.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1785156225);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":22,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("captchadetection.lastSubmission", 1785156);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "e9a875fe-c904-4214-91f6-b5c8c403ba92");
user_pref("datareporting.dau.cachedUsageProfileID", "72f921dc-1ead-48ed-8d75-205bec275e78");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1785156266206");
user_pref("distribution.iniFile.exists.appversion", "140.10.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.redhat.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECCpHg9R6mW9zBAg/376PhqgwYQ==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260416072800");
user_pref("extensions.lastAppVersion", "140.10.0");
user_pref("extensions.lastPlatformVersion", "140.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f794444b-1ad7-4983-9dd0-7fe24c928bc1\",\"newtab@mozilla.org\":\"5883294d-5564-4443-88b4-fc520dca2622\",\"pictureinpicture@mozilla.org\":\"76fda472-e933-4deb-82c6-62c4f8a143bd\",\"addons-search-detection@mozilla.com\":\"a8cd710e-c73b-48dc-886e-334ab91cedd0\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"default-theme@mozilla.org\":\"3a9a82af-ee6b-478d-884d-00be60edac27\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398878, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1785156224);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1785156224);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 1);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "f776a2a0-6eb9-4b10-85fe-50f5e078f8cf");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECHMnytfkBqbSBAi4miC5UKJdLw==");
user_pref("toolkit.profiles.storeID", "2136c041");
user_pref("toolkit.startup.last_success", 1785156177);
user_pref("toolkit.telemetry.cachedClientID", "0a08f435-9fbc-44fc-8cfa-80a9289e3a13");
user_pref("toolkit.telemetry.cachedProfileGroupID", "e0292e55-f2f5-4a18-8244-8a0063d9971f");
user_pref("toolkit.telemetry.previousBuildID", "20260416072800");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
